[[ d1_databases ]]
binding = "DB"
database_name = "artora"
database_id = "d4658898-a398-4788-9d0e-cdf755ce2cd9"
migrations_dir = "db/migrate"

[[ kv_namespaces ]]
binding = "SESSION_KV"
id = "${KV_ID}"
preview_id = "${PREVIEW_KV_ID}"
